//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Discount.DB_Model.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\v11.0;AttachDbFilename=\"C:\\Users\\vizio\\Documents\\Visual Stu" +
            "dio 2013\\Projects\\E-Discount\\E-Discount\\App_Data\\EDiscount.mdf\";Integrated Secur" +
            "ity=True;Connect Timeout=30")]
        public string EDiscountConnectionString {
            get {
                return ((string)(this["EDiscountConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\v11.0;AttachDbFilename=\"C:\\Users\\vizio\\Documents\\Visual Stu" +
            "dio 2013\\Projects\\E-Discount\\E-Discount.Web\\App_Data\\EDiscount.mdf\";Integrated S" +
            "ecurity=True")]
        public string EDiscountConnectionString1 {
            get {
                return ((string)(this["EDiscountConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\v11.0;AttachDbFilename=\"C:\\Users\\vizio\\Documents\\Visual Stu" +
            "dio 2013\\WebSites\\E-Discount.Web\\App_Data\\EDiscount.mdf\";Integrated Security=Tru" +
            "e;Connect Timeout=30")]
        public string EDiscountConnectionString2 {
            get {
                return ((string)(this["EDiscountConnectionString2"]));
            }
        }
    }
}
